### ISSUE TITLE
Random browser user agents or random user agents?

### ISSUE THREAD

**Issue by japborst** [alecxe/scrapy-fake-useragent#10]
Hi,

I got a question. The user agents from useragentstring.com also includes crawlers and bots. Does that mean that those are included in the random generation of user agents or are only browsers included?

Thanks!

**Comment by alecxe** [comment]
@japborst good question. Since we use `fake-useragent` package and it uses the real-world stats (available [here](http://www.w3schools.com/browsers/default.asp)), the random user agent you get would only contain the browsers presented on this page which are Chrome, IE, Firefox, Safari or Opera. The user agent strings can though be not only 'desktop' but 'mobile' as well. Thanks.

**Comment by japborst** [comment]
Thanks for the update @alecxe. With some auto throttling it works perfectly btw! :-)
